# Generated by Django 5.1.1 on 2024-11-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('DESCARTADOR', 'Descartador'), ('CATADOR', 'Catador')], max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('pontuacao_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Descarte',
            fields=[
                ('id_descarte', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status_descarte', models.CharField(choices=[('PENDENTE', 'pendente'), ('APROVADO', 'aprovado'), ('REPROVADO', 'reprovado')], default='PENDENTE', max_length=10)),
                ('nome_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecobag.usuario')),
            ],
        ),
    ]
