# Generated by Django 5.1.1 on 2024-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecobag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('DESCARTADOR', 'Descartador'), ('CATADOR', 'Catador')], max_length=12),
        ),
    ]
