# Generated by Django 5.1.1 on 2024-12-05 19:26

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecobag', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='cadastro_produto', variations={'thumb': (124, 124)}, verbose_name='Imagem do Produto'),
        ),
    ]
